routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware'=>'auth'
	], function(){
Route::resource('/clientes', 'ClienteController');

Route::post('clientes/buscar', 'ClienteController@buscar');

}

);

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'cliente';

    protected $fillable = ['nombre','apellido','correo','celular','telefono1','telefono2'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;
use Validator;
use Illuminate\Support\Facades\Input;

class ClienteController extends Controller
{
    
    public function index()
    {

    	$clientes = Cliente::orderBy('id','asc')
    				->paginate(5);

        return view('cliente.index',['clientes'=>$clientes]);	
    }

    public function show($id)
    {
    	$cliente = Cliente::find($id);

    	if($cliente) {
    		return view('cliente.show',['cliente'=>$cliente]);
    	}
    }

    public function create()
    {
        return view('cliente.create');	
    }

    public function store(Request $request)
    {
    	$validation = $this->validator($request->all());

    	if($validation->fails()) {
    		return redirect()->back()->withErrors($validator->errors())->withInput();
    	}

    	$cliente = new Cliente();

    	$cliente->nombre = $request->nombre;
    	$cliente->apellido = $request->apellido;
    	$cliente->correo = $request->correo;
    	if($request->celular)
    		$cliente->celular = $request->celular;
    	if($request->telefono1)
    		$cliente->telefono1 = $request->telefono1;
    	if($request->telefono2)
    		$cliente->telefono2 = $request->telefono2;
    	
    	$cliente->save();

    	return redirect()->route('clientes.index')->with('mensaje','Cliente insertado correctamente.');
    }

    public function edit($id) 
    {
    	$cliente = Cliente::find($id);

   		return view('cliente.edit',['cliente'=>$cliente]);
    }

    public function update(Request $request, $id)
    {
		$validator = $this->validator($request->all());

    	if($validator->fails()) {

    	}

    	$cliente = Cliente::find($id);

    	$input = $request->all();

    	$cliente->fill($input)->save();

    	return redirect()->route('clientes.index')->with('mensaje','Cliente actualizado correctamente.');

    }

    public function destroy($id)
    {
    	$cliente = Cliente::find($id);

    	$cliente->delete();

    	return redirect('clientes')->with('mensaje','Cliente eliminado correctamente');
    }

    protected function validator(array $data)
    {
    	return Validator::make($data,[
    		'nombre' => 'required|string',
    		'apellido' => 'required|string',
    		'correo' => 'required|email'
    	]);
    }

    public function buscar()
    {
    	$buscar=Input::get('buscar');

    	if (empty($buscar)) {
    		return redirect()->back();    		
    	} 

    	$clientes = Cliente::where('nombre', 'LIKE', $buscar.'%')
    				->orWhere('celular', 'LIKE', $buscar.'%')
    				->orWhere('telefono1', 'LIKE', $buscar.'%')
    				->orWhere('telefono2', 'LIKE', $buscar.'%')
   					->orderBy('id','asc')
    				->paginate(5);

    	if($clientes->count()){
        	return view('cliente.resultado',['clientes'=>$clientes]);	
    	} else {
        	return view('cliente.resultado')->with('mensaje','No hay resultado de la busqueda');	
    	}
    	
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/cliente/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-8">
            <div class="card">
                <div class="card-header"><strong>Crear Cliente</strong></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <form class="form-horizontal" action="{{url('clientes')}}" method="POST">
       					<input type="hidden" name="_token" value="{{ csrf_token() }}">

                    	<div class="form-group">
				            <label for="nombre">Nombre</label>
				            <span class="text-danger">*</span>
				            <input id ="nombre" type="text" autofocus class="form-control" name="nombre" required >
						</div>
                    	<div class="form-group">
				            <label for="apellido">Apellido</label>
				            <span class="text-danger">*</span>
				            <input id ="apellido" type="text" class="form-control" name="apellido" required >
						</div>
                    	<div class="form-group">
				            <label for="correo">Correo Electrónico</label>
				            <input id ="correo" type="email" class="form-control" name="correo" >
						</div>
						<div class="form-group">
				            <label for="celular">Celular</label>
				            <input id ="celular" type="text" class="form-control" name="celular" >
						</div>
						<div class="form-group">
				            <label for="telefono1">Telefono 01</label>
				            <input id ="apellido" type="text" class="form-control" name="telefono1" >
						</div>
						<div class="form-group">
				            <label for="telefono2">Telefono 02</label>
				            <input id ="apellido" type="text" class="form-control" name="telefono2" >
						</div>
						<button class="btn btn-success">Guardar</button>
						<a class="btn btn-primary" href="{{url('clientes')}}">Volver</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cliente/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-8">
            <div class="card">
                <div class="card-header"><strong>Actualizar Cliente # {{$cliente->id}}</strong></div>

                <div class="card-body">

                    <form class="form-horizontal" action="{{url('clientes',$cliente->id)}}" method="POST">
       					<input type="hidden" name="_token" value="{{ csrf_token() }}">
						<input type="hidden" name="_method" value="PUT">

                    	<div class="form-group">
				            <label for="nombre">Nombre</label>
				            <span class="text-danger">*</span>
				            <input id ="nombre" type="text" autofocus class="form-control" name="nombre" value="{{ $cliente->nombre }}" required >
						</div>
                    	<div class="form-group">
				            <label for="apellido">Apellido</label>
				            <span class="text-danger">*</span>
				            <input id ="apellido" type="text" class="form-control" name="apellido" value="{{ $cliente->apellido }}" required >
						</div>
                    	<div class="form-group">
				            <label for="correo">Correo Electrónico</label>
				            <input id ="correo" type="email" class="form-control" name="correo" value="{{ $cliente->correo }}" >
						</div>
						<div class="form-group">
				            <label for="celular">Celular</label>
				            <input id ="celular" type="text" class="form-control" name="celular" value="{{ $cliente->celular }}" >
						</div>
						<div class="form-group">
				            <label for="telefono1">Telefono 01</label>
				            <input id ="apellido" type="text" class="form-control" name="telefono1" value="{{ $cliente->telefono1 }}" >
						</div>
						<div class="form-group">
				            <label for="telefono2">Telefono 02</label>
				            <input id ="apellido" type="text" class="form-control" name="telefono2" value="{{ $cliente->apellido }}" >
						</div>
						<button class="btn btn-success">Actualizar</button>
						<a class="btn btn-primary" href="{{url('clientes')}}">Volver</a>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cliente/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header"><strong>Listado de Clientes</strong></div>

                <div class="card-body">
                    @if (isset($mensaje))
                        <div class='bg-warning' style='padding: 10px'>
                            {{$mensaje}}
                        </div>
                    @endif
                    <div class="col-md-12">
                    	<a href="{{url('clientes/create')}}" class="btn btn-primary"><span class="fa fa-plus"></span> Crear Cliente</a>
                    </div>
                    <br>
                    @if (isset($clientes))
                    <div class="col-md-offset-8">
				    	<div class="form-group">
				            <div class="input-group col-md-6 pull-right">
                                <span class="input-group-addon">
                                    <input id="buscar" type="text" class="form-control" name="buscar" placeholder="Buscar...">
				                </span>   
				            </div>
						</div>
			    	</div>
                    <div class="table-responsive">
                    	<table class="table">
                    		<thead>
                    			<tr>
                    				<th>#</th>
                    				<th>Nombre</th>
                    				<th>Apellido</th>
                    				<th>Correo Eléctronico</th>
                    				<th>Celular</th>
                    				<th></th>
                    			</tr>
                    		</thead>
                    		<tbody class="datos">
                    			@foreach($clientes as $cliente)
                    			<tr>
                                    <td>
	                                	<a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->id }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->nombre }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->apellido }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->correo }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->celular }}
	                                	</a>
	                                </td>
	                                <td>
	                                	<a href="{{url('/clientes',$cliente->id)}}" class="btn btn-success">Ver</a>
	                                	<a href="{{route('clientes.edit',$cliente->id)}}" class="btn btn-warning">Editar</a>
                                        <form action="{{ url('clientes', $cliente->id) }}" method="POST" onsubmit="if(confirm('Estas seguro de Eliminar el cliente?')){ return true} else {return false};">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <button type="submit" class="btn btn-danger pull-right" title="Eliminar Cliente">Eliminar</button>
                                                
                                        </form>
	                                </td>
                    			</tr>
                    			@endforeach
                    		</tbody>
                    		
                    	</table>
						<div class="pagination">
							{{ $clientes->links() }}
						</div>
                    </div>
                    @else
                        <h2>No hay resultado</h2>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cliente/resultado.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header"><strong>Resultado de Búsqueda</strong>
                </div>

                <div class="card-body">
                    @if (isset($clientes))
                    <a class="btn btn-primary pull-right" href="{{url('/clientes')}}">Volver</a>

                    <div class="table-responsive">
                    	<table class="table">
                    		<thead>
                    			<tr>
                    				<th>#</th>
                    				<th>Nombre</th>
                    				<th>Apellido</th>
                    				<th>Correo Eléctronico</th>
                    				<th>Celular</th>
                    				<th></th>
                    			</tr>
                    		</thead>
                    		<tbody>
                    			@foreach($clientes as $cliente)
                    			<tr>
                                    <td>
	                                	<a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->id }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->nombre }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->apellido }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->correo }}
	                                	</a>
	                                </td>
	                                <td><a href="{{ url('clientes',$cliente->id) }}">
	                                		{{ $cliente->celular }}
	                                	</a>
	                                </td>
	                                <td>
	                                	<a href="{{url('/clientes',$cliente->id)}}" class="btn btn-success">Ver</a>
	                                	<a href="{{route('clientes.edit',$cliente->id)}}" class="btn btn-warning">Editar</a>
                                        <form action="{{ url('clientes', $cliente->id) }}" method="POST" onsubmit="if(confirm('Estas seguro de Eliminar el cliente?')){ return true} else {return false};">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <button type="submit" class="btn btn-danger pull-right" title="Eliminar Cliente">Eliminar</button>
                                                
                                        </form>
	                                </td>
                    			</tr>
                    			@endforeach
                    		</tbody>
                    		
                    	</table>
						<div class="">
							{{ $clientes->links() }}
						</div>
                    </div>
                    @else
                        <div>
                            <a class="btn btn-primary" href="{{url('/clientes')}}">Volver</a>                        
                        </div>
                        <h2>No hay resultado</h2>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/cliente/show.blade.php
@extends('layouts.app')

@section('content')


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12 col-lg-12">
            <div class="card">
                <div class="card-header"><strong>Detalle del Cliente # {{ $cliente->id }}</strong></div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="table-responsive">
		                    <table class="table table-bordered table-hover table-striped">
		                        <thead>
		                        </thead>
		                        <tbody>
		                                <tr>
			                                <td><strong>ID</strong></td>
			                                <td>{{ $cliente->id }}</td>
			                            <tr>
			                            <tr>
			                                <td><strong>Nombre</strong></td>
			                                <td>{{ $cliente->nombre }}</td>
			                            <tr>
			                            <tr>
			                                <td><strong>Apellido</strong></td>
			                                <td>{{ $cliente->apellido }}</td>
			                            <tr>
			                            <tr>
			                                <td><strong>Correo Electrónico</strong></td>
			                                <td>{{ $cliente->correo }}</td>
			                            <tr>
			                            <tr>
			                                <td><strong>Celular</strong></td>
			                                <td>{{ $cliente->celular }}</td>
			                            <tr>
			                      		<tr>
			                                <td><strong>Telefono 01</strong></td>
			                                <td>{{ $cliente->telefono1 }}</td>
			                            <tr>
			                            <tr>
			                                <td><strong>Telefono 02</strong></td>
			                                <td>{{ $cliente->telefono2 }}</td>
			                            <tr>		                       		                       		                        
			                    </tbody>
		                    </table>
		                </div>
		                <div>
		                	<a href="{{url('/clientes')}}" class="btn btn-primary">Volver</a>
		                </div> 
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div>
                        <a class="btn btn-default btn-warning" href="{{url('clientes')}}">Acceder a la Agenda</a>                    
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#buscar').keyup(function() {
            var exp = new RegExp($(this).val(), 'i');
            if($("#buscar").val().length > 0 ){
                $('.pagination').hide();
                $('.datos tr').hide();
                $('.datos tr').filter(function() {
                    return exp.test($(this).text());
                }).show();
            } else {
                $('.pagination').show();
            }
            

        })
    })
</script>
</body>
</html>